-- ============================================================
-- ARECIMA / AURELIA — Complete MySQL Database Schema
-- Import this file once in phpMyAdmin (full database import).
--
-- Includes: 24 tables, indexes, foreign keys, default admin,
--           Tunisia shipping, store settings, sample catalog.
--
-- Admin login:  Admin
-- Password:     Admin@2026
--
-- Compatible: MySQL 5.7+ / MariaDB 10.3+ (OVH, cPanel, etc.)
-- IDs are 32-char hex (generated by PHP), not UUID() defaults.
-- ============================================================

SET NAMES utf8mb4;
SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';
SET FOREIGN_KEY_CHECKS = 0;
SET time_zone = '+00:00';

-- ---------------------------------------------------------------------------
-- Clean reinstall (drops all aurelia_* tables — safe for first import)
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS `aurelia_page_views`;
DROP TABLE IF EXISTS `aurelia_visitor_sessions`;
DROP TABLE IF EXISTS `aurelia_cart_items`;
DROP TABLE IF EXISTS `aurelia_favorites`;
DROP TABLE IF EXISTS `aurelia_order_timeline`;
DROP TABLE IF EXISTS `aurelia_order_items`;
DROP TABLE IF EXISTS `aurelia_orders`;
DROP TABLE IF EXISTS `aurelia_reviews`;
DROP TABLE IF EXISTS `aurelia_product_images`;
DROP TABLE IF EXISTS `aurelia_product_tags`;
DROP TABLE IF EXISTS `aurelia_products`;
DROP TABLE IF EXISTS `aurelia_blog_tags`;
DROP TABLE IF EXISTS `aurelia_blog_posts`;
DROP TABLE IF EXISTS `aurelia_customer_tags`;
DROP TABLE IF EXISTS `aurelia_customers`;
DROP TABLE IF EXISTS `aurelia_coupons`;
DROP TABLE IF EXISTS `aurelia_newsletter_subscribers`;
DROP TABLE IF EXISTS `aurelia_inventory_log`;
DROP TABLE IF EXISTS `aurelia_activity_log`;
DROP TABLE IF EXISTS `aurelia_notifications`;
DROP TABLE IF EXISTS `aurelia_settings`;
DROP TABLE IF EXISTS `aurelia_shipping_zones`;
DROP TABLE IF EXISTS `aurelia_categories`;
DROP TABLE IF EXISTS `aurelia_admin_users`;

-- ========================
-- 1. ADMIN USERS
-- ========================

CREATE TABLE `aurelia_admin_users` (
  `id` CHAR(32) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `full_name` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `role` ENUM('super_admin', 'admin', 'manager', 'viewer') NOT NULL DEFAULT 'viewer',
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `last_login_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_admin_email` (`email`),
  KEY `idx_admin_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================
-- 2. CATEGORIES
-- ========================

CREATE TABLE `aurelia_categories` (
  `id` CHAR(32) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `name_fr` VARCHAR(255) NOT NULL,
  `name_en` VARCHAR(255) NULL,
  `name_ar` VARCHAR(255) NULL,
  `description_fr` TEXT NULL,
  `description_en` TEXT NULL,
  `description_ar` TEXT NULL,
  `image_url` TEXT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_category_slug` (`slug`),
  KEY `idx_category_active` (`is_active`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================
-- 3. PRODUCTS
-- ========================

CREATE TABLE `aurelia_products` (
  `id` CHAR(32) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `sku` VARCHAR(100) NULL,
  `barcode` VARCHAR(100) NULL,
  `category_id` CHAR(32) NULL,
  `name_fr` VARCHAR(255) NOT NULL,
  `name_en` VARCHAR(255) NULL,
  `name_ar` VARCHAR(255) NULL,
  `description_fr` TEXT NULL,
  `description_en` TEXT NULL,
  `description_ar` TEXT NULL,
  `ingredients_fr` TEXT NULL,
  `ingredients_en` TEXT NULL,
  `ingredients_ar` TEXT NULL,
  `price` DECIMAL(10,3) NOT NULL,
  `original_price` DECIMAL(10,3) NULL,
  `cost_price` DECIMAL(10,3) NOT NULL DEFAULT 0.000,
  `stock` INT NOT NULL DEFAULT 0,
  `low_stock_threshold` INT NOT NULL DEFAULT 10,
  `weight_grams` INT NULL,
  `size` VARCHAR(100) NULL,
  `rating` DECIMAL(2,1) NOT NULL DEFAULT 0.0,
  `review_count` INT NOT NULL DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `is_new` TINYINT(1) NOT NULL DEFAULT 0,
  `is_best_seller` TINYINT(1) NOT NULL DEFAULT 0,
  `seo_title` VARCHAR(255) NULL,
  `seo_description` TEXT NULL,
  `seo_keywords` TEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_product_slug` (`slug`),
  UNIQUE KEY `uq_product_sku` (`sku`),
  KEY `idx_product_category` (`category_id`),
  KEY `idx_product_active` (`is_active`),
  KEY `idx_product_created` (`created_at`),
  CONSTRAINT `fk_product_category` FOREIGN KEY (`category_id`) REFERENCES `aurelia_categories` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================
-- 4. PRODUCT IMAGES
-- ========================

CREATE TABLE `aurelia_product_images` (
  `id` CHAR(32) NOT NULL,
  `product_id` CHAR(32) NOT NULL,
  `url` TEXT NOT NULL,
  `alt_text` VARCHAR(255) NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `is_primary` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_image_product` (`product_id`),
  KEY `idx_image_primary` (`product_id`, `is_primary`),
  CONSTRAINT `fk_image_product` FOREIGN KEY (`product_id`) REFERENCES `aurelia_products` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================
-- 5. PRODUCT TAGS
-- ========================

CREATE TABLE `aurelia_product_tags` (
  `id` CHAR(32) NOT NULL,
  `product_id` CHAR(32) NOT NULL,
  `tag` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_product_tag` (`product_id`, `tag`),
  CONSTRAINT `fk_ptag_product` FOREIGN KEY (`product_id`) REFERENCES `aurelia_products` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================
-- 6. CUSTOMERS (CRM)
-- ========================

CREATE TABLE `aurelia_customers` (
  `id` CHAR(32) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(50) NULL,
  `country` VARCHAR(100) NULL,
  `city` VARCHAR(100) NULL,
  `address` TEXT NULL,
  `postal_code` VARCHAR(20) NULL,
  `is_subscribed` TINYINT(1) NOT NULL DEFAULT 0,
  `total_orders` INT NOT NULL DEFAULT 0,
  `total_spent` DECIMAL(12,3) NOT NULL DEFAULT 0.000,
  `last_order_at` DATETIME NULL,
  `notes` TEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_customer_email` (`email`),
  KEY `idx_customer_email` (`email`),
  KEY `idx_customer_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================
-- 7. CUSTOMER TAGS
-- ========================

CREATE TABLE `aurelia_customer_tags` (
  `id` CHAR(32) NOT NULL,
  `customer_id` CHAR(32) NOT NULL,
  `tag` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_customer_tag` (`customer_id`, `tag`),
  CONSTRAINT `fk_ctag_customer` FOREIGN KEY (`customer_id`) REFERENCES `aurelia_customers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================
-- 8. ORDERS
-- ========================

CREATE TABLE `aurelia_orders` (
  `id` CHAR(32) NOT NULL,
  `order_number` VARCHAR(50) NOT NULL,
  `customer_id` CHAR(32) NULL,
  `customer_name` VARCHAR(255) NOT NULL,
  `customer_email` VARCHAR(255) NOT NULL,
  `customer_phone` VARCHAR(40) NULL,
  `status` ENUM('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded') NOT NULL DEFAULT 'pending',
  `payment_status` ENUM('pending', 'paid', 'failed', 'refunded') NOT NULL DEFAULT 'pending',
  `payment_method` VARCHAR(100) NULL,
  `subtotal` DECIMAL(12,3) NOT NULL DEFAULT 0.000,
  `shipping` DECIMAL(10,3) NOT NULL DEFAULT 0.000,
  `discount` DECIMAL(10,3) NOT NULL DEFAULT 0.000,
  `tax` DECIMAL(10,3) NOT NULL DEFAULT 0.000,
  `total` DECIMAL(12,3) NOT NULL DEFAULT 0.000,
  `shipping_address` TEXT NULL,
  `shipping_city` VARCHAR(100) NULL,
  `shipping_country` VARCHAR(100) NULL,
  `shipping_postal_code` VARCHAR(20) NULL,
  `tracking_number` VARCHAR(255) NULL,
  `coupon_code` VARCHAR(50) NULL,
  `notes` TEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_order_number` (`order_number`),
  KEY `idx_order_customer` (`customer_id`),
  KEY `idx_order_status` (`status`),
  KEY `idx_order_payment` (`payment_status`),
  KEY `idx_order_created` (`created_at`),
  CONSTRAINT `fk_order_customer` FOREIGN KEY (`customer_id`) REFERENCES `aurelia_customers` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================
-- 9. ORDER ITEMS
-- ========================

CREATE TABLE `aurelia_order_items` (
  `id` CHAR(32) NOT NULL,
  `order_id` CHAR(32) NOT NULL,
  `product_id` CHAR(32) NULL,
  `product_name` VARCHAR(255) NOT NULL,
  `product_sku` VARCHAR(100) NULL,
  `quantity` INT NOT NULL DEFAULT 1,
  `unit_price` DECIMAL(10,3) NOT NULL,
  `total` DECIMAL(10,3) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_oitem_order` (`order_id`),
  KEY `idx_oitem_product` (`product_id`),
  CONSTRAINT `fk_oitem_order` FOREIGN KEY (`order_id`) REFERENCES `aurelia_orders` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_oitem_product` FOREIGN KEY (`product_id`) REFERENCES `aurelia_products` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================
-- 10. ORDER TIMELINE
-- ========================

CREATE TABLE `aurelia_order_timeline` (
  `id` CHAR(32) NOT NULL,
  `order_id` CHAR(32) NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  `note` TEXT NULL,
  `created_by` CHAR(32) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_timeline_order` (`order_id`),
  CONSTRAINT `fk_timeline_order` FOREIGN KEY (`order_id`) REFERENCES `aurelia_orders` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_timeline_admin` FOREIGN KEY (`created_by`) REFERENCES `aurelia_admin_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================
-- 11. COUPONS
-- ========================

CREATE TABLE `aurelia_coupons` (
  `id` CHAR(32) NOT NULL,
  `code` VARCHAR(50) NOT NULL,
  `description` TEXT NULL,
  `discount_type` ENUM('percentage', 'fixed') NOT NULL,
  `discount_value` DECIMAL(10,3) NOT NULL,
  `min_order_amount` DECIMAL(10,3) NULL,
  `max_uses` INT NULL,
  `used_count` INT NOT NULL DEFAULT 0,
  `starts_at` DATETIME NULL,
  `expires_at` DATETIME NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_coupon_code` (`code`),
  KEY `idx_coupon_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================
-- 12. REVIEWS
-- ========================

CREATE TABLE `aurelia_reviews` (
  `id` CHAR(32) NOT NULL,
  `product_id` CHAR(32) NOT NULL,
  `customer_id` CHAR(32) NULL,
  `customer_name` VARCHAR(255) NOT NULL,
  `rating` TINYINT UNSIGNED NOT NULL,
  `title` VARCHAR(255) NULL,
  `body` TEXT NULL,
  `is_verified` TINYINT(1) NOT NULL DEFAULT 0,
  `is_approved` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_review_product` (`product_id`),
  KEY `idx_review_approved` (`product_id`, `is_approved`),
  CONSTRAINT `fk_review_product` FOREIGN KEY (`product_id`) REFERENCES `aurelia_products` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_review_customer` FOREIGN KEY (`customer_id`) REFERENCES `aurelia_customers` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================
-- 13. BLOG POSTS
-- ========================

CREATE TABLE `aurelia_blog_posts` (
  `id` CHAR(32) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `author_id` CHAR(32) NULL,
  `title_fr` VARCHAR(255) NOT NULL,
  `title_en` VARCHAR(255) NULL,
  `title_ar` VARCHAR(255) NULL,
  `content_fr` LONGTEXT NULL,
  `content_en` LONGTEXT NULL,
  `content_ar` LONGTEXT NULL,
  `excerpt_fr` TEXT NULL,
  `excerpt_en` TEXT NULL,
  `excerpt_ar` TEXT NULL,
  `category_fr` VARCHAR(100) NULL,
  `category_en` VARCHAR(100) NULL,
  `category_ar` VARCHAR(100) NULL,
  `image_url` TEXT NULL,
  `read_time` INT NOT NULL DEFAULT 5,
  `is_published` TINYINT(1) NOT NULL DEFAULT 0,
  `seo_title` VARCHAR(255) NULL,
  `seo_description` TEXT NULL,
  `published_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_blog_slug` (`slug`),
  KEY `idx_blog_published` (`is_published`, `published_at`),
  CONSTRAINT `fk_blog_author` FOREIGN KEY (`author_id`) REFERENCES `aurelia_admin_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================
-- 14. BLOG TAGS
-- ========================

CREATE TABLE `aurelia_blog_tags` (
  `id` CHAR(32) NOT NULL,
  `post_id` CHAR(32) NOT NULL,
  `tag` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_blog_tag` (`post_id`, `tag`),
  CONSTRAINT `fk_btag_post` FOREIGN KEY (`post_id`) REFERENCES `aurelia_blog_posts` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================
-- 15. NEWSLETTER
-- ========================

CREATE TABLE `aurelia_newsletter_subscribers` (
  `id` CHAR(32) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(100) NULL,
  `source` VARCHAR(100) NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `subscribed_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `unsubscribed_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_newsletter_email` (`email`),
  KEY `idx_newsletter_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================
-- 16. FAVORITES
-- ========================

CREATE TABLE `aurelia_favorites` (
  `id` CHAR(32) NOT NULL,
  `customer_id` CHAR(32) NOT NULL,
  `product_id` CHAR(32) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_favorite` (`customer_id`, `product_id`),
  CONSTRAINT `fk_fav_customer` FOREIGN KEY (`customer_id`) REFERENCES `aurelia_customers` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_fav_product` FOREIGN KEY (`product_id`) REFERENCES `aurelia_products` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================
-- 17. CART (persistent)
-- ========================

CREATE TABLE `aurelia_cart_items` (
  `id` CHAR(32) NOT NULL,
  `customer_id` CHAR(32) NOT NULL,
  `product_id` CHAR(32) NOT NULL,
  `quantity` INT NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_cart_item` (`customer_id`, `product_id`),
  CONSTRAINT `fk_cart_customer` FOREIGN KEY (`customer_id`) REFERENCES `aurelia_customers` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_cart_product` FOREIGN KEY (`product_id`) REFERENCES `aurelia_products` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================
-- 18. VISITOR SESSIONS (analytics)
-- ========================

CREATE TABLE `aurelia_visitor_sessions` (
  `id` CHAR(32) NOT NULL,
  `visitor_id` VARCHAR(255) NOT NULL,
  `ip_address` VARCHAR(45) NULL,
  `device` ENUM('desktop', 'mobile', 'tablet') NULL,
  `browser` VARCHAR(100) NULL,
  `os` VARCHAR(100) NULL,
  `country` VARCHAR(100) NULL,
  `city` VARCHAR(100) NULL,
  `referrer_source` VARCHAR(255) NULL,
  `landing_page` VARCHAR(500) NULL,
  `pages_viewed` INT NOT NULL DEFAULT 0,
  `duration_seconds` INT NOT NULL DEFAULT 0,
  `is_bounce` TINYINT(1) NOT NULL DEFAULT 0,
  `started_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_session_started` (`started_at`),
  KEY `idx_session_visitor` (`visitor_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================
-- 19. PAGE VIEWS (analytics)
-- ========================

CREATE TABLE `aurelia_page_views` (
  `id` CHAR(32) NOT NULL,
  `session_id` CHAR(32) NULL,
  `page_path` VARCHAR(500) NOT NULL,
  `page_title` VARCHAR(255) NULL,
  `time_on_page_seconds` INT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_pv_session` (`session_id`),
  KEY `idx_pv_created` (`created_at`),
  CONSTRAINT `fk_pv_session` FOREIGN KEY (`session_id`) REFERENCES `aurelia_visitor_sessions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================
-- 20. INVENTORY LOG
-- ========================

CREATE TABLE `aurelia_inventory_log` (
  `id` CHAR(32) NOT NULL,
  `product_id` CHAR(32) NOT NULL,
  `change_amount` INT NOT NULL,
  `reason` VARCHAR(255) NOT NULL,
  `reference_id` CHAR(32) NULL,
  `created_by` CHAR(32) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_invlog_product` (`product_id`),
  CONSTRAINT `fk_invlog_product` FOREIGN KEY (`product_id`) REFERENCES `aurelia_products` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_invlog_admin` FOREIGN KEY (`created_by`) REFERENCES `aurelia_admin_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================
-- 21. SETTINGS (key-value JSON)
-- ========================

CREATE TABLE `aurelia_settings` (
  `id` CHAR(32) NOT NULL,
  `key` VARCHAR(255) NOT NULL,
  `value` JSON NOT NULL,
  `updated_by` CHAR(32) NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_setting_key` (`key`),
  CONSTRAINT `fk_setting_admin` FOREIGN KEY (`updated_by`) REFERENCES `aurelia_admin_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================
-- 22. ADMIN NOTIFICATIONS
-- ========================

CREATE TABLE `aurelia_notifications` (
  `id` CHAR(32) NOT NULL,
  `admin_user_id` CHAR(32) NULL,
  `type` VARCHAR(100) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `body` TEXT NULL,
  `is_read` TINYINT(1) NOT NULL DEFAULT 0,
  `link` VARCHAR(500) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_notif_user` (`admin_user_id`),
  KEY `idx_notif_read` (`is_read`),
  CONSTRAINT `fk_notif_admin` FOREIGN KEY (`admin_user_id`) REFERENCES `aurelia_admin_users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================
-- 23. SHIPPING ZONES
-- ========================

CREATE TABLE `aurelia_shipping_zones` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `countries` TEXT NOT NULL,
  `base_cost` DECIMAL(10,3) NOT NULL DEFAULT 0.000,
  `free_threshold` DECIMAL(10,3) NULL,
  `estimated_days_min` INT NULL,
  `estimated_days_max` INT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_shipping_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ========================
-- 24. ACTIVITY LOG (audit)
-- ========================

CREATE TABLE `aurelia_activity_log` (
  `id` CHAR(32) NOT NULL,
  `admin_user_id` CHAR(32) NULL,
  `action` VARCHAR(100) NOT NULL,
  `entity_type` VARCHAR(100) NOT NULL,
  `entity_id` CHAR(32) NULL,
  `details` JSON NULL,
  `ip_address` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_actlog_user` (`admin_user_id`),
  KEY `idx_actlog_entity` (`entity_type`, `entity_id`),
  KEY `idx_actlog_created` (`created_at`),
  CONSTRAINT `fk_actlog_admin` FOREIGN KEY (`admin_user_id`) REFERENCES `aurelia_admin_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- SEED DATA
-- ============================================================

-- Admin (login: Admin / Admin@2026)
INSERT INTO `aurelia_admin_users` (`id`, `email`, `full_name`, `password_hash`, `role`, `is_active`)
VALUES (
  'b2222222222222222222222222222222',
  'admin@arecima.tn',
  'Admin',
  '$2y$10$5IUcsLsUYcZ4hpJTm9nTZemtW5iGwB8cxpmMkJyNIFr/Avt0dtKf.',
  'super_admin',
  1
) ON DUPLICATE KEY UPDATE
  `full_name` = VALUES(`full_name`),
  `password_hash` = VALUES(`password_hash`),
  `role` = VALUES(`role`),
  `is_active` = 1;

-- Tunisia shipping
INSERT INTO `aurelia_shipping_zones` (`id`, `name`, `countries`, `base_cost`, `free_threshold`, `is_active`)
VALUES (
  'a11111111111111111111111111111111',
  'Tunisia',
  'Tunisia,TN',
  7.000,
  150.000,
  1
) ON DUPLICATE KEY UPDATE
  `base_cost` = VALUES(`base_cost`),
  `free_threshold` = VALUES(`free_threshold`),
  `is_active` = 1;

-- Store settings
INSERT INTO `aurelia_settings` (`id`, `key`, `value`, `updated_by`) VALUES
('c1111111111111111111111111111111', 'store', '{"name":"Arecima","tagline":"Beauté Rituelle","currency":"TND","locale_default":"fr"}', 'b2222222222222222222222222222222'),
('c2222222222222222222222222222222', 'contact', '{"email":"admin@arecima.tn","phone":"","address":"Tunisia"}', 'b2222222222222222222222222222222'),
('c3333333333333333333333333333333', 'shipping', '{"free_threshold":150,"default_cost":7,"country":"Tunisia"}', 'b2222222222222222222222222222222'),
('c4444444444444444444444444444444', 'checkout', '{"payment_methods":["cod"],"cod_label":"Paiement à la livraison"}', 'b2222222222222222222222222222222'),
('c5555555555555555555555555555555', 'facebook_pixel', '{"enabled":false,"pixel_id":"","track_page_view":true,"track_view_content":true,"track_add_to_cart":true,"track_initiate_checkout":true,"track_purchase":true,"track_add_to_wishlist":true,"test_event_code":""}', 'b2222222222222222222222222222222')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`);

-- Sample coupon (10% off, min 50 TND)
INSERT INTO `aurelia_coupons` (`id`, `code`, `description`, `discount_type`, `discount_value`, `min_order_amount`, `max_uses`, `is_active`)
VALUES (
  'd1111111111111111111111111111111',
  'WELCOME10',
  'Bienvenue — 10% de réduction',
  'percentage',
  10.000,
  50.000,
  NULL,
  1
) ON DUPLICATE KEY UPDATE `is_active` = 1;

-- Sample categories
INSERT INTO `aurelia_categories` (`id`, `slug`, `name_fr`, `name_en`, `name_ar`, `sort_order`, `is_active`) VALUES
('e1111111111111111111111111111111', 'serums', 'Sérums', 'Serums', 'سيروم', 1, 1),
('e2222222222222222222222222222222', 'cremes', 'Crèmes', 'Creams', 'كريمات', 2, 1),
('e3333333333333333333333333333333', 'nettoyants', 'Nettoyants', 'Cleansers', 'منظفات', 3, 1)
ON DUPLICATE KEY UPDATE `name_fr` = VALUES(`name_fr`), `is_active` = 1;

-- Sample products (for immediate storefront / checkout testing)
INSERT INTO `aurelia_products` (
  `id`, `slug`, `sku`, `category_id`, `name_fr`, `name_en`, `name_ar`,
  `description_fr`, `price`, `original_price`, `stock`, `is_active`, `is_new`, `is_best_seller`
) VALUES
(
  'f1111111111111111111111111111111',
  'serum-eclat-vitamine-c',
  'ARE-SERUM-001',
  'e1111111111111111111111111111111',
  'Sérum Éclat Vitamine C',
  'Vitamin C Glow Serum',
  'سيروم توهج فيتامين سي',
  'Sérum concentré pour un teint lumineux et unifié. Application matin et soir.',
  89.000,
  109.000,
  50,
  1, 1, 1
),
(
  'f2222222222222222222222222222222',
  'creme-hydratante-nuit',
  'ARE-CREME-001',
  'e2222222222222222222222222222222',
  'Crème Hydratante Nuit',
  'Night Hydrating Cream',
  'كريم ترطيب ليلي',
  'Texture riche, réparation nocturne pour peaux sèches et sensibles.',
  75.000,
  NULL,
  40,
  1, 0, 1
),
(
  'f3333333333333333333333333333333',
  'gel-nettoyant-doux',
  'ARE-NETT-001',
  'e3333333333333333333333333333333',
  'Gel Nettoyant Doux',
  'Gentle Cleansing Gel',
  'جل تنظيف لطيف',
  'Nettoie en douceur sans dessécher. Convient à tous types de peau.',
  45.000,
  NULL,
  60,
  1, 1, 0
)
ON DUPLICATE KEY UPDATE `stock` = VALUES(`stock`), `is_active` = 1;

-- Sample blog post (draft)
INSERT INTO `aurelia_blog_posts` (
  `id`, `slug`, `author_id`, `title_fr`, `title_en`, `excerpt_fr`, `is_published`, `read_time`
) VALUES (
  'g1111111111111111111111111111111',
  'routine-soin-peau',
  'b2222222222222222222222222222222',
  'Votre routine soin en 3 étapes',
  'Your 3-step skincare routine',
  'Découvrez une routine simple et efficace pour une peau éclatante.',
  0,
  5
) ON DUPLICATE KEY UPDATE `title_fr` = VALUES(`title_fr`);

-- Sample approved reviews (homepage testimonials)
INSERT INTO `aurelia_reviews` (`id`, `product_id`, `customer_name`, `rating`, `title`, `body`, `is_verified`, `is_approved`) VALUES
('h1111111111111111111111111111111', 'f1111111111111111111111111111111', 'Yasmine B.', 5, 'Éclat visible', 'Le Sérum Éclat Vitamine C a transformé ma peau en deux semaines. Teint plus lumineux et uniforme.', 1, 1),
('h2222222222222222222222222222222', 'f2222222222222222222222222222222', 'Amira K.', 5, 'Texture luxueuse', 'La Crème Hydratante Nuit est mon produit préféré — texture riche qui pénètre sans laisser de film gras.', 1, 1),
('h3333333333333333333333333333333', 'f3333333333333333333333333333333', 'Leila M.', 5, 'Douceur au quotidien', 'Le Gel Nettoyant Doux nettoie parfaitement sans irriter ma peau sensible. Toute ma routine est Arecima.', 1, 1)
ON DUPLICATE KEY UPDATE `is_approved` = 1;

SET FOREIGN_KEY_CHECKS = 1;

-- ============================================================
-- Done. 24 tables created + seed data loaded.
-- Verify: SELECT COUNT(*) FROM aurelia_products;  (expect 3)
-- Admin:   Admin / Admin@2026
-- Coupon:  WELCOME10 (10% off, min 50 TND)
-- ============================================================
